// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASF2IlObjD3hMqAZ9cI2LIH9Li9q7D6vk',
    appId: '1:647800160228:web:3d341d84892234114311f1',
    messagingSenderId: '647800160228',
    projectId: 'aurashield-a5e04',
    authDomain: 'aurashield-a5e04.firebaseapp.com',
    databaseURL: 'https://aurashield-a5e04-default-rtdb.firebaseio.com',
    storageBucket: 'aurashield-a5e04.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj89quB5c83710GAROePBsfY7L9taFStc',
    appId: '1:647800160228:android:651c86d956f42ba14311f1',
    messagingSenderId: '647800160228',
    projectId: 'aurashield-a5e04',
    databaseURL: 'https://aurashield-a5e04-default-rtdb.firebaseio.com',
    storageBucket: 'aurashield-a5e04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC02Nobir4c4-T7sJsgnskC30ANRJHON0w',
    appId: '1:647800160228:ios:3e57e5ef7cadc3e04311f1',
    messagingSenderId: '647800160228',
    projectId: 'aurashield-a5e04',
    databaseURL: 'https://aurashield-a5e04-default-rtdb.firebaseio.com',
    storageBucket: 'aurashield-a5e04.firebasestorage.app',
    iosBundleId: 'com.example.aurashield',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC02Nobir4c4-T7sJsgnskC30ANRJHON0w',
    appId: '1:647800160228:ios:3e57e5ef7cadc3e04311f1',
    messagingSenderId: '647800160228',
    projectId: 'aurashield-a5e04',
    databaseURL: 'https://aurashield-a5e04-default-rtdb.firebaseio.com',
    storageBucket: 'aurashield-a5e04.firebasestorage.app',
    iosBundleId: 'com.example.aurashield',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASF2IlObjD3hMqAZ9cI2LIH9Li9q7D6vk',
    appId: '1:647800160228:web:2ef9ff0f04bfef314311f1',
    messagingSenderId: '647800160228',
    projectId: 'aurashield-a5e04',
    authDomain: 'aurashield-a5e04.firebaseapp.com',
    databaseURL: 'https://aurashield-a5e04-default-rtdb.firebaseio.com',
    storageBucket: 'aurashield-a5e04.firebasestorage.app',
  );
}
